# Puppet Dashboard Auth
# https://192.168.58.10
# Username: admin
# Password: password

$num_agents=2
$agent_gui=false
$agent_memory='1024'
$agent_cpus='1'
$git_env = `git rev-parse --abbrev-ref HEAD`.strip


Vagrant.configure(2) do |config|

  # Global Configuration
  config.vm.box = "bento/centos-6.7"

  # hostmanager configuration
  # Plugin needed
  # vagrant plugin install vagrant-hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  # MoM Configuration
  config.vm.define "puppet-mom" do |puppet_mom_config|

    # r10k configuration
    # Plugin needed
    # vagrant plugin install vagrant-r10k
    puppet_mom_config.r10k.puppet_dir = "../"
    puppet_mom_config.r10k.puppetfile_path = "../Puppetfile"
    puppet_mom_config.r10k.module_path = "../modules"

    puppet_mom_config.vm.host_name = "puppet-mom.localvm"

    puppet_mom_config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = 'puppet-mom'
      vb.cpus = '2'
      vb.memory = '6144'
    end

    puppet_mom_config.vm.synced_folder '.', "/vagrant", disabled: true
    puppet_mom_config.vm.synced_folder '..', "/vagrant"

    puppet_mom_config.vm.network "private_network", ip: "192.168.58.10"

    puppet_mom_config.vm.provision :shell, :path => './scripts/init.sh'

    puppet_mom_config.vm.provision "puppet" do |puppet|
      puppet.environment_path = "./environments"
      puppet.environment = "fake"
      puppet.manifests_path = "./environments/fake/manifests"
      puppet.manifest_file = "site.pp"
    end

    puppet_mom_config.vm.provision :shell, :path => './scripts/puppet-run.sh'

  end #End MoM Configuration

  # CM01 Configuration
  config.vm.define "puppet-cm01" do |puppet_cm01_config|
    puppet_cm01_config.vm.host_name = "puppet-cm01.localvm"

    puppet_cm01_config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = 'puppet-cm01'
      vb.cpus = '1'
      vb.memory = '4096'
    end

    puppet_cm01_config.vm.synced_folder '.', "/vagrant", disabled: true
    puppet_cm01_config.vm.synced_folder '..', "/vagrant"

    puppet_cm01_config.vm.network "private_network", ip: "192.168.58.11"

    puppet_cm01_config.vm.provision :shell, :path => './scripts/init.sh'

    puppet_cm01_config.vm.provision "puppet_server" do |puppet|
      puppet.puppet_server = "puppet-mom.localvm"
      puppet.options = "-t --environment #{$git_env}"
    end
  end #End CM01 Configuration

  # Create Agents
  (1..$num_agents).each do |i|
    config.vm.define vm_name = "agent%02d" % i do |config|
      config.vm.box = "bento/centos-6.7"

      config.vm.hostname = "#{vm_name}.localvm"

      config.vm.provider "virtualbox" do |vb|
        vb.gui = $agent_gui
        vb.name = vm_name
        vb.memory = $agent_memory
        vb.cpus = $agent_cpus
      end

      ip = "192.168.58.#{i+100}"
      config.vm.network :private_network, ip: ip

      config.vm.synced_folder '.', "/vagrant", disabled: true
      config.vm.synced_folder '..', "/vagrant"

      config.vm.provision :shell, :path => './scripts/init.sh'

      case vm_name
      when 'agent01'
        $puppet_server = 'puppet-cm01.localvm'
      when 'agent02'
        $puppet_server = 'puppet-mom.localvm'
      else
        $puppet_server = 'puppet-cm01.localvm'
      end

      config.vm.provision "puppet_server" do |puppet|
        puppet.puppet_server = $puppet_server
        puppet.options = "-t --environment #{$git_env}"
      end

    end
  end # End Agents' Configuration
end
